/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-10 12:05:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class AboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>瓜大4S</title>\r\n");
      out.write("    ");
 String result="";
       if(request.getAttribute("result")!=null)result=(String)request.getAttribute("result");
     
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("   <div class=\"top\">\r\n");
      out.write("     <div class=\"tlp\">\r\n");
      out.write("       <image src=\"/MySystem/picture/npu.jpg\" height=\"70px\" width=\"70px\">\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"index.jsp\">首页</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">故障查询</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"ArticleListServlet\">汽修资料</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"test/AboutUs.jsp\">关于企业</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">联系我们</a>\r\n");
      out.write("    </div>\r\n");
      out.write("      <div class=\"in\">\r\n");
      out.write("        <a href=\"index.jsp\">登陆</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"in1\">\r\n");
      out.write("        <a href=\"test/NewUser.jsp\">注册新用户</a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"body2\">\r\n");
      out.write("     <br><br>\r\n");
      out.write("     <p>关于我们</p>\r\n");
      out.write("     <div class=\"bodyin\">\r\n");
      out.write("                 三石科技有限公司，采用先进互联网云端技术，\r\n");
      out.write("                 专注为汽车维修、美容系统打造，提供智能化解决方案。<br>\r\n");
      out.write("                 目前客户遍及全国，上千家汽车服务企业使用三石科技管理业务，提升效益。\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"body3\">\r\n");
      out.write("     <div class=\"box1\">\r\n");
      out.write("       February 2015\r\n");
      out.write("       <div class=\"boxin\">\r\n");
      out.write("                       公司成立<br>确定云端汽车服务软<br>件为核心产品方向\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"box2\">\r\n");
      out.write("       October 2016\r\n");
      out.write("       <div class=\"boxin\">\r\n");
      out.write("                       第一款产品上线<br>首款产品推出上线,并<br>确定每周迭代更新原则\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("      <div class=\"box1\">\r\n");
      out.write("       January 2017\r\n");
      out.write("       <div class=\"boxin\">\r\n");
      out.write("                       首次重大更新<br>功能界面各方面全面提升<br>，客户满意度大增\r\n");
      out.write("       </div>\r\n");
      out.write("     </div><br><br><br>\r\n");
      out.write("     <div class=\"box3\">\r\n");
      out.write("       October 2017\r\n");
      out.write("       <div class=\"boxin\">\r\n");
      out.write("                       第一款产品上线<br>首款产品推出上线,并<br>确定每周迭代更新原则\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"bottom\">NWPU MIS | Copyright © 2017 </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
