/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-09 05:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import bean.*;;

public final class NewOrderResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'MyJsp.jsp' starting page</title>\r\n");
      out.write("    \r\n");

  Orders o=(Orders)request.getAttribute("order");
 
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <table ;width:800px\">\r\n");
      out.write("             <tr align=\"center\">\r\n");
      out.write("             <td>\r\n");
      out.write("               <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("             </td>\r\n");
      out.write("             <td>订单号</td>\r\n");
      out.write("             <td>车牌号</td>\r\n");
      out.write("             <td>姓名</td>\r\n");
      out.write("             <td>业务类型</td>\r\n");
      out.write("             <td>负责技师</td>\r\n");
      out.write("             <td>日期</td>\r\n");
      out.write("             <td>当前状态</td>\r\n");
      out.write("             <td>备注</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("               <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("             </td>\r\n");
      out.write("            <td>");
      out.print(o.getOId() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(o.getCarId() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(o.getName() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(o.getOType() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(o.getWorkId() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(o.getODate() );
      out.write("</td>            \r\n");
      out.write("            <td>");
      out.print(o.getIfOk() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(o.getOMark() );
      out.write("</td>           \r\n");
      out.write("          </tr>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
