/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-10 12:04:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import bean.*;;

public final class NewOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>创建新订单</title>\r\n");

  List<Worker> list=(List<Worker>)request.getAttribute("list");
 
      out.write(" \r\n");
      out.write(" <script src=\"bean/jquery-3.2.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <script>\r\n");
      out.write("   $(function(){\r\n");
      out.write("    \t\t$(\".act1\").click(function(e){\r\n");
      out.write("    \t\t\tvar $form1=$(this).next();\r\n");
      out.write("    \t\t\tif($form1.is(\":visible\")){\r\n");
      out.write("    \t\t\t\t$form1.hide();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\t$form1.show();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t})\r\n");
      out.write(" </script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("   function check(form){\r\n");
      out.write("\t    with(form){\r\n");
      out.write("\t      if(name.value==\"\"||carId.value==\"\"||oType.value==\"\"){\r\n");
      out.write("\t        alert(\"信息输入不完整\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write(" </script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("   <p align=\"center\">创建新订单</p>\r\n");
      out.write("   <div class=\"newbody\">\r\n");
      out.write("    <div class=\"neworder\">\r\n");
      out.write("     <form method=\"post\" action=\"OrderServlet\" name=\"form\" onsubmit=\"return check(this);\">\r\n");
      out.write("       <p>姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名：<input type=\"text\" name=\"name\" value=\"\"></p>\r\n");
      out.write("       <p>车&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;号：<input type=\"text\" name=\"carId\" value=\"\"></p>\r\n");
      out.write("       <p>业务类型：清洗:<input type=\"radio\" checked=\"checked\" name=\"oType\" value=\"清洗\"> 维修：\r\n");
      out.write("       <input type=\"radio\" name=\"oType\" value=\"维修\">保养：\r\n");
      out.write("       <input type=\"radio\" name=\"oType\" value=\"保养\">美容：\r\n");
      out.write("       <input type=\"radio\" name=\"oType\" value=\"美容\"></p>\r\n");
      out.write("       <p>指定技师：<input type=\"text\" name=\"workId\" value=\"\"><a>(可以为空)</a></p>\r\n");
      out.write("       <p>备注信息：<input type=\"text\" name=\"oMark\" value=\"\"></p>\r\n");
      out.write("       <input type=\"submit\" value=\"确认提交\" class=\"btn1\" name=\"submit\">\r\n");
      out.write("     </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <p align=\"center\" class=\"act1\">点击查看技师列表</p>\r\n");
      out.write("   <div class=\"neworder\" style=\"display:none;\">\r\n");
      out.write("     <table>\r\n");
      out.write("       <tr align=\"center\">\r\n");
      out.write("             <td>\r\n");
      out.write("               <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("             </td>\r\n");
      out.write("             <td>工号</td>\r\n");
      out.write("             <td>技师姓名</td>\r\n");
      out.write("             <td>性别</td>\r\n");
      out.write("             <td>业务类型</td>\r\n");
      out.write("             <td>联系电话</td>\r\n");
      out.write("             <td>技能等级</td>\r\n");
      out.write("             <td>等待人数</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("       ");
 
       for(Worker w:list){
       
      out.write("\r\n");
      out.write("         <tr align=\"center\">\r\n");
      out.write("           <td>\r\n");
      out.write("             <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("           </td>\r\n");
      out.write("           <td>");
      out.print(w.getWorkId() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(w.getWName() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(w.getWSex() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(w.getWType() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(w.getWPhone() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(w.getWClass() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(w.getWLine() );
      out.write("</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("     </table>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
