/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-22 17:18:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class NewUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>注册页面</title>\r\n");
      out.write("    \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t  function check(form){\r\n");
      out.write("\t    with(form){\r\n");
      out.write("\t      if(name.value==\"\"||phone.value==\"\"||IDCard.value==\"\"||password.value==\"\"||password1.value==\"\"){\r\n");
      out.write("\t        alert(\"信息输入不完整\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(password.value!=password1.value){\r\n");
      out.write("\t        alert(\"两次输入密码不一致，请重新输入\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(IDCard.value.length!=18){\r\n");
      out.write("\t        alert(\"证件格式错误\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("     <div class=\"top\">\r\n");
      out.write("     <div class=\"tlp\">\r\n");
      out.write("       <image src=\"/MySystem/picture/npu.jpg\" height=\"70px\" width=\"70px\">\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"index.jsp\">首页</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">故障查询</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"ArticleListServlet\">汽修资料</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">关于企业</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">联系我们</a>\r\n");
      out.write("    </div>\r\n");
      out.write("      <div class=\"in\">\r\n");
      out.write("        <a href=\"index.jsp\">登陆</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"in1\">\r\n");
      out.write("        <a href=\"test/NewUser.jsp\">注册新用户</a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"body1\">\r\n");
      out.write("    <div class=\"form\">\r\n");
      out.write("     <p> 实名登记</p>\r\n");
      out.write("     <form method=\"post\" action=\"AddNewUserServlet\" name=\"form\" onsubmit=\"return check(this);\">\r\n");
      out.write("       <pre>\r\n");
      out.write("姓    名：<input type=\"text\" name=\"name\" value=\"\"><br>\r\n");
      out.write("性    别：男<input type=\"radio\" checked=\"checked\" name=\"sex\" value=\"male\"> 女<input type=\"radio\" name=\"sex\" value=\"female\"><br>\r\n");
      out.write("手    机：<input type=\"text\" name=\"phone\" value=\"\"><br>\r\n");
      out.write("证件号码：<input type=\"text\" name=\"IDCard\" value=\"\"><br>\r\n");
      out.write("输入密码：<input type=\"password\" name=\"password\" value=\"\"><br>\r\n");
      out.write("确认密码：<input type=\"password\" name=\"password1\" value=\"\"><br><br>\r\n");
      out.write("<input type=\"submit\" value=\"确认提交\" class=\"btn1\" name=\"submit\">\r\n");
      out.write("        </pre>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"NUbody\">\r\n");
      out.write("      <image src=\"/MySystem/picture/car6.jpg\" height=\"150px\" width=\"350px\"><br><br><br><br>\r\n");
      out.write("      <image src=\"/MySystem/picture/npu2.jpg\" height=\"150px\" width=\"350px\">\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"bottom\">NWPU MIS | Copyright © 2017 </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
