/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-23 06:39:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import bean.*;

public final class person_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>个人主页</title>\r\n");
      out.write("    \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t");

	  String name;
	  if(request.getAttribute("name")!="null"&&request.getAttribute("name")!=null)
	    name=(String)request.getAttribute("name");
	  else name="<a href=>未登录</a>";
	  User u=(User)request.getAttribute("user");
	  List<Car> carlist=(List<Car>)request.getAttribute("carlist");
	  Notice n=(Notice)request.getAttribute("notice");
	  List<Orders> olist=(List<Orders>)request.getAttribute("olist");
	  
	 
      out.write("\r\n");
      out.write("\t<script language=\"javascript\">\r\n");
      out.write("\t  function realSysTime(clock){\r\n");
      out.write("\t    var now=new Date();\r\n");
      out.write("\t    var year=now.getFullYear();\r\n");
      out.write("\t    var month=now.getMonth();\r\n");
      out.write("\t    var date=now.getDate();\r\n");
      out.write("\t    var day=now.getDay();\r\n");
      out.write("\t    var hour=now.getHours();\r\n");
      out.write("\t    var minu=now.getMinutes();\r\n");
      out.write("\t    var sec=now.getSeconds();\r\n");
      out.write("\t    month=month+1;\r\n");
      out.write("\t    var arr_week=new Array(\"星期日\",\"星期一\",\"星期二\",\"星期三\",\"星期四\",\"星期五\",\"星期六\");\r\n");
      out.write("\t    var week=arr_week[day];\r\n");
      out.write("\t    var time=year+\"年 \"+month+\"月 \"+date+\"日 \"+week;\r\n");
      out.write("\t    if(hour<10){\r\n");
      out.write("\t       time=time+\" 0\"+hour;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t       time=time+\" \"+hour;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if(minu<10){\r\n");
      out.write("\t      time=time+\":0\"+minu;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t      time=time+\":\"+minu;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if(sec<10){\r\n");
      out.write("\t      time=time+\":0\"+sec;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t      time=time+\":\"+sec;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    clock.innerHTML=\"当前时间：\"+time;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  window.onload=function(){\r\n");
      out.write("\t    window.setInterval(\"realSysTime(clock)\", 1000);\r\n");
      out.write("\t  }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script language=\"javascript\">\r\n");
      out.write("\t  function checkcar(form){\r\n");
      out.write("\t    with(form){\r\n");
      out.write("\t      if(carId.value==\"\"){\r\n");
      out.write("\t        alert(\"请输入车牌号\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(carType.value==\"\"){\r\n");
      out.write("\t        alert(\"请输入车型\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(color.value==\"\"){\r\n");
      out.write("\t        alert(\"请输入颜色\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(startDate.value==\"\"){\r\n");
      out.write("\t        alert(\"请输入出厂日期\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(cMark.value==\"\"){\r\n");
      out.write("\t        alert(\"请输入备注信息\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script language=\"javascript\">\r\n");
      out.write("\t   function check(user){\r\n");
      out.write("\t    with(user){\r\n");
      out.write("\t      if(name.value==\"\"||phone.value==\"\"||IDCard.value==\"\"){\r\n");
      out.write("\t        alert(\"信息输入不完整\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(IDCard.value.length!=18){\r\n");
      out.write("\t        alert(\"证件格式错误\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"bean/jquery-3.2.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t  $(function(){\r\n");
      out.write("    \t\t$(\".act1\").click(function(e){\r\n");
      out.write("    \t\t\tvar $form1=$(this).next();\r\n");
      out.write("    \t\t\tif($form1.is(\":visible\")){\r\n");
      out.write("    \t\t\t\t$form1.hide();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\t$form1.show();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t})\r\n");
      out.write("    \t$(function(){\r\n");
      out.write("    \t\t$(\".leftfont\").click(function(e){\r\n");
      out.write("    \t\t\tvar $form2=$(\".act1\");\r\n");
      out.write("    \t\t\tif($form2.is(\":visible\")){\r\n");
      out.write("    \t\t\t\t$form2.hide();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\t$form2.show();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t})\r\n");
      out.write("       $(function(){\r\n");
      out.write("        $(\".act4\").click(function(e){\r\n");
      out.write("         var w=window.open(\"OrderServlet\", \"oderOperation\", \"width=800px,height=600px,top=100px,left=450px\");\r\n");
      out.write("        })\r\n");
      out.write("       })\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"top\">\r\n");
      out.write("     <div class=\"tlp\">\r\n");
      out.write("       <image src=\"/MySystem/picture/npu.jpg\" height=\"70px\" width=\"70px\">\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"index.jsp\">首页</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">故障查询</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"ArticleListServlet\">汽修资料</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"test/AboutUs.jsp\">关于企业</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"test/AboutUs.jsp\">联系我们</a>\r\n");
      out.write("    </div>\r\n");
      out.write("      <div class=\"in2\">\r\n");
      out.write("        ");
      out.print(name );
      out.write("您好，欢迎回来\r\n");
      out.write("        <a href=\"index.jsp\">退出</a>\r\n");
      out.write("      </div>      \r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"body1\">\r\n");
      out.write("     <div class=\"bodyleft\">\r\n");
      out.write("       <div class=\"left\">\r\n");
      out.write("         <div class=\"leftpic\">\r\n");
      out.write("            <image src=\"/MySystem/picture/pic1.jpg\" heigth=\"90px\" width=\"100px\" >\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"leftfont\">\r\n");
      out.write("         ");
      out.print(name );
      out.write("<br>\r\n");
      out.write("                        我的资料\r\n");
      out.write("         </div>\r\n");
      out.write("         <br>\r\n");
      out.write("         <image src=\"/MySystem/picture/mess1.png\" heigth=\"50px\" width=\"50px\" ><br>\r\n");
      out.write("         <div class=\"mess\">\r\n");
      out.write("                             亲爱的");
      out.print(name );
      out.write("<br>\r\n");
      out.write("           <div class=\"mess1\">\r\n");
      out.write("             <div id=\"clock\"></div>\r\n");
      out.write("             今日天气：");
      out.print(n.getWeather() );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"http://www.weather.com.cn/weather/101110101.shtml\">详情</a><br>\r\n");
      out.write("             今日油价：90号汽油：");
      out.print(n.getOil90() );
      out.write("<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;93号汽油：");
      out.print(n.getOil93() );
      out.write("\r\n");
      out.write("     <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;97号汽油：");
      out.print(n.getOil97() );
      out.write("\r\n");
      out.write("     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("     <a href=\"http://www.bitauto.com/youjia/xian/?WT.srch=1\">详情</a><br>\r\n");
      out.write("             交通状况：");
      out.print(n.getRoad() );
      out.write("<br>\r\n");
      out.write("             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;通畅路段：友谊西路\r\n");
      out.write("             &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"\">详情</a><br>\r\n");
      out.write("             我的业务：<a href=\"\">详情</a><br>\r\n");
      out.write("           </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"bodyright\">\r\n");
      out.write("       <div class=\"data\">\r\n");
      out.write("        <p class=\"act1\">个人资料</p>\r\n");
      out.write("        <table style=\"display:none;width:650px\">\r\n");
      out.write("          <tr align=\"center\">\r\n");
      out.write("           <td>\r\n");
      out.write("             <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp&nbsp\r\n");
      out.write("           </td>\r\n");
      out.write("           <td>姓名</td>\r\n");
      out.write("           <td>证件号</td>\r\n");
      out.write("           <td>联系方式</td>\r\n");
      out.write("           <td>性别</td>\r\n");
      out.write("           <td>当前城市</td>\r\n");
      out.write("           <td>操作</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr align=\"center\">\r\n");
      out.write("           <td>\r\n");
      out.write("             <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp&nbsp\r\n");
      out.write("           </td>\r\n");
      out.write("           <td>");
      out.print(u.getName() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(u.getIDCard() );
      out.write("</td>                             \r\n");
      out.write("           <td>");
      out.print(u.getPhone() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(u.getSex() );
      out.write("</td>              \r\n");
      out.write("           <td>西安市</td>\r\n");
      out.write("           <td>\r\n");
      out.write("             <a href=\"test/UpdatePerson.jsp?name=");
      out.print(name);
      out.write("&sex=");
      out.print(u.getSex());
      out.write("&phone=");
      out.print(u.getPhone());
      out.write("&IDCard=");
      out.print(u.getIDCard());
      out.write("\">\r\n");
      out.write("                                点击修改资料</a></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("       </table>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"car\">\r\n");
      out.write("       <p class=\"act1\">车辆</p>\r\n");
      out.write("         <table style=\"display:none;\">\r\n");
      out.write("          <tr align=\"center\">\r\n");
      out.write("           <td>\r\n");
      out.write("             <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("           </td>\r\n");
      out.write("           <td>车牌号</td>\r\n");
      out.write("           <td>车型</td>\r\n");
      out.write("           <td>颜色</td>\r\n");
      out.write("           <td>出厂日期</td>\r\n");
      out.write("           <td>备注</td>\r\n");
      out.write("           <td>操作</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("           ");
 
             for(Car c:carlist){
            
      out.write("\r\n");
      out.write("         <tr align=\"center\">\r\n");
      out.write("           <td>\r\n");
      out.write("             <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("           </td>\r\n");
      out.write("           <td>");
      out.print(c.getCarId() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(c.getCarType() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(c.getColor() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(c.getStartDate() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(c.getCMark() );
      out.write("</td>\r\n");
      out.write("           <td><a href=\"MainPageServlet?carId=");
      out.print(c.getCarId() );
      out.write("\"  onclick=\"return confirm('真的要删除么')\">点击删除</a></td>\r\n");
      out.write("         </tr> \r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("           <form action=\"OperateServlet\" method=\"get\" name=\"\" onsubmit=\"return checkcar(this)\">\r\n");
      out.write("             <tr align=\"center\">\r\n");
      out.write("               <td>\r\n");
      out.write("                 <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("               </td>\r\n");
      out.write("               <td><input type=\"text\" name=\"carId\" value=\"\"  style=\"width:70px;\"></td>\r\n");
      out.write("               <td><input type=\"text\" name=\"carType\" value=\"\"  style=\"width:70px;\"></td>\r\n");
      out.write("               <td><input type=\"text\" name=\"color\" value=\"\"  style=\"width:70px;\"></td>\r\n");
      out.write("               <td><input type=\"text\" name=\"startDate\" value=\"\" style=\"width:70px;\"></td>\r\n");
      out.write("               <td><input type=\"text\" name=\"cMark\" value=\"\" style=\"width:70px;\"></td>\r\n");
      out.write("               <input type=\"hidden\" name=\"IDCard\" value=\"");
      out.print(u.getIDCard());
      out.write("\">\r\n");
      out.write("               <td><input type=\"submit\" name=\"submit\" value=\"添加车辆\"></td>\r\n");
      out.write("             </tr>\r\n");
      out.write("           </form>\r\n");
      out.write("         </table>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"order\">\r\n");
      out.write("         <p class=\"act1\">我的业务</p>\r\n");
      out.write("           <table style=\"display:none;width:900px\">\r\n");
      out.write("             <tr align=\"center\">\r\n");
      out.write("             <td>\r\n");
      out.write("               <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("             </td>\r\n");
      out.write("             <td>订单号</td>\r\n");
      out.write("             <td>车牌号</td>\r\n");
      out.write("             <td>姓名</td>\r\n");
      out.write("             <td>业务类型</td>\r\n");
      out.write("             <td>负责技师</td>\r\n");
      out.write("             <td>日期</td>\r\n");
      out.write("             <td>价格</td>\r\n");
      out.write("             <td>当前状态</td>\r\n");
      out.write("             <td>备注</td>\r\n");
      out.write("             <td>操作订单</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("             ");
 
             for(Orders o:olist){
            
      out.write("\r\n");
      out.write("         <tr align=\"center\">\r\n");
      out.write("           <td>\r\n");
      out.write("             <image src=\"/MySystem/picture/data1.png\" width=\"50px\" height=\"40px\">&nbsp;&nbsp;\r\n");
      out.write("           </td>             \r\n");
      out.write("           <td>");
      out.print(o.getOId() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getCarId() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getName() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getOType() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getWorkId() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getODate() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getSum() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getIfOk() );
      out.write("</td>\r\n");
      out.write("           <td>");
      out.print(o.getOMark() );
      out.write("</td>\r\n");
      out.write("           <td><a href=\"Operate2Servlet?carId=");
      out.print(o.getCarId() );
      out.write("\" target=\"view_frame\">操作</a></td>\r\n");
      out.write("           </tr >\r\n");
      out.write("           ");
} 
      out.write("\r\n");
      out.write("           <tr align=\"center\"><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>\r\n");
      out.write("             <td><a class=\"act4\">添加新订单</a></td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           </table>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"bottom\">NWPU MIS | Copyright © 2017 </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
