/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-04 05:35:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class UpdatePerson_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>修改个人资料</title>\r\n");
      out.write("    ");

	  String name=request.getParameter("name");
	  String sex=new String(request.getParameter("sex").getBytes("ISO-8859-1"),"UTF-8");
	  String phone=request.getParameter("phone");
	  String IDCard=request.getParameter("IDCard");
	 
      out.write("\r\n");
      out.write("\t <script type=\"text/javascript\">\r\n");
      out.write("\t  function check(form){\r\n");
      out.write("\t    with(form){\r\n");
      out.write("\t      if(name.value==\"\"||phone.value==\"\"||IDCard.value==\"\"){\r\n");
      out.write("\t        alert(\"信息输入不完整\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(IDCard.value.length!=18){\r\n");
      out.write("\t        alert(\"证件格式错误\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("\t   function check(form1){\r\n");
      out.write("\t    with(form1){\r\n");
      out.write("\t      if(newpassword.value==\"\"||password1.value==\"\"||password.value==\"\"){\r\n");
      out.write("\t        alert(\"信息输入不完整\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      if(password.value!=password1.value){\r\n");
      out.write("\t        alert(\"两次输入密码不一致，请重新输入\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }\r\n");
      out.write("\t</script>\r\n");
      out.write("    <script src=\"bean/jquery-3.2.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t  $(function(){\r\n");
      out.write("    \t\t$(\".act1\").click(function(e){\r\n");
      out.write("    \t\t\tvar $form1=$(this).next();\r\n");
      out.write("    \t\t\tif($form1.is(\":visible\")){\r\n");
      out.write("    \t\t\t\t$form1.hide();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\t$form1.show();\r\n");
      out.write("\t\t\t\t\te.stopPropagation();\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t})\r\n");
      out.write("    </script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"top\">\r\n");
      out.write("     <div class=\"tlp\">\r\n");
      out.write("       <image src=\"/MySystem/picture/npu.jpg\" height=\"70px\" width=\"70px\">\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"http://localhost:8080/MySystem/index.jsp\">首页</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">故障查询</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"ArticleListServlet\">汽修资料</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">关于企业</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"linka\">\r\n");
      out.write("       <a href=\"\">联系我们</a>\r\n");
      out.write("    </div>\r\n");
      out.write("      <div class=\"in2\">\r\n");
      out.write("        ");
      out.print(name );
      out.write("您好，欢迎回来\r\n");
      out.write("        <a href=\"http://localhost:8080/MySystem/index.jsp\">退出</a>\r\n");
      out.write("      </div>      \r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"body1\">\r\n");
      out.write("    <div class=\"form1\">\r\n");
      out.write("     <p>修改资料</p>\r\n");
      out.write("     <form method=\"post\" action=\"OperateServlet\" name=\"form\" onsubmit=\"return check(this);\">\r\n");
      out.write("       <p>姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名：<input type=\"text\" name=\"name\" value=\"");
      out.print(name);
      out.write("\"></p>\r\n");
      out.write("       <p>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：男<input type=\"radio\" checked=\"checked\" name=\"sex\" value=\"male\"> 女<input type=\"radio\" name=\"sex\" value=\"female\"></p>\r\n");
      out.write("       <p>手&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;机：<input type=\"text\" name=\"phone\" value=\"");
      out.print(phone);
      out.write("\"></p>\r\n");
      out.write("       <input type=\"hidden\" name=\"IDCard\" value=\"");
      out.print(IDCard);
      out.write("\">\r\n");
      out.write("       <p>证件号码：");
      out.print(IDCard );
      out.write("</p>\r\n");
      out.write("<input type=\"submit\" value=\"确认提交\" class=\"btn1\" name=\"submit\">\r\n");
      out.write("        </form>\r\n");
      out.write("    <p class=\"act1\">修改密码</p> \r\n");
      out.write("      <div class=\"act2\">\r\n");
      out.write("        <form method=\"post\" action=\"Operate2Servlet\" name=\"form1\" onsubmit=\"return check(this)\">\r\n");
      out.write("          <p>输入旧密码：<input type=\"password\" name=\"password\" value=\"\"></p>\r\n");
      out.write("          <p>输入新密码：<input type=\"password\" name=\"password1\" value=\"\"></p>\r\n");
      out.write("          <p>确认新密码：<input type=\"password\" name=\"newpassword\" value=\"\"></p>\r\n");
      out.write("          <p><input type=\"submit\" value=\"确认修改\" class=\"btn1\" name=\"submit\"></p>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"NUbody1\">\r\n");
      out.write("      <image src=\"/MySystem/picture/car6.jpg\" height=\"150px\" width=\"350px\"><br><br><br><br>\r\n");
      out.write("      <image src=\"/MySystem/picture/npu2.jpg\" height=\"150px\" width=\"350px\">\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"bottom\">NWPU MIS | Copyright © 2017 </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
