/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-09 10:59:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import jdbc.*;

public final class ProList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>查看物品信息</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("   function check(f){\r\n");
      out.write("     with(f){\r\n");
      out.write("       if(count.value==\"\"){\r\n");
      out.write("       alert(\"数量不可以为空！\");\r\n");
      out.write("       count.focus();\r\n");
      out.write("       return false;\r\n");
      out.write("       }\r\n");
      out.write("     }\r\n");
      out.write("   }\r\n");
      out.write("   function check1(f){\r\n");
      out.write("     confirm();\r\n");
      out.write("   }\r\n");
      out.write("   function check3(f){\r\n");
      out.write("\t  with(f){\r\n");
      out.write("\t   if(name.value==\"\"){\r\n");
      out.write("\t     alert(\"名称不可以为空!\");\r\n");
      out.write("\t     name.focus();\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   if(price.value==\"\"){\r\n");
      out.write("\t     alert(\"价格不可以为空!\");\r\n");
      out.write("\t     price.focus();\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   if(num.value==\"\"){\r\n");
      out.write("\t     alert(\"数量不可以为空!\");\r\n");
      out.write("\t     num.focus();\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   if(unit.value==\"\"){\r\n");
      out.write("\t     alert(\"单元不可以为空!\");\r\n");
      out.write("\t     unit.focus();\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t  }\r\n");
      out.write("\t }\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("   <table align=\"center\" border=\"1\" >\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td align=\"center\" colspan=\"7\">\r\n");
      out.write("     <h2>所有商品信息</h2>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr align=\"center\">\r\n");
      out.write("    <td>ID</td>\r\n");
      out.write("    <td>商品名称</td>\r\n");
      out.write("    <td>价格</td>\r\n");
      out.write("    <td>数量</td>\r\n");
      out.write("    <td>单位</td>\r\n");
      out.write("    <td>修改数量</td>\r\n");
      out.write("    <td>删除</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("     ");

     List<Product> list=(List<Product>)request.getAttribute("list");
     for(Product p:list){         
     
      out.write("\r\n");
      out.write("     <tr align=\"center\">\r\n");
      out.write("     <td>0");
      out.print(p.getId() );
      out.write("</td>\r\n");
      out.write("     <td>");
      out.print(p.getName() );
      out.write("</td>\r\n");
      out.write("     <td>");
      out.print(p.getPrice() );
      out.write("</td>\r\n");
      out.write("     <td>");
      out.print(p.getNum() );
      out.write("</td>\r\n");
      out.write("     <td>");
      out.print(p.getUnit() );
      out.write("</td>\r\n");
      out.write("     <td><form action=\"UpdateServlet\" name=\"form\" method=\"post\" onsubmit=\"return check(this);\">\r\n");
      out.write("           <input type=\"hidden\" name=\"id\" value=\"");
      out.print(p.getId());
      out.write("\">\r\n");
      out.write("           <input type=\"text\" name=\"count\" size=\"3\">\r\n");
      out.write("           <input type=\"submit\" value=\"修改\">\r\n");
      out.write("         </form>\r\n");
      out.write("     </td>\r\n");
      out.write("     <td>\r\n");
      out.write("     <a href=\"DeleteServlet?id=");
      out.print(p.getId() );
      out.write("\"  onclick=\"return confirm('真的要删除么')\">删除</a>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     ");
} 
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td align=\"center\" colspan=\"7\" bgcolor=\"white\">\r\n");
      out.write("       ");
      out.print(request.getAttribute("bar") );
      out.write("\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>    \r\n");
      out.write("    <tr>\r\n");
      out.write("     <td align=\"center\" colspan=\"7\" bgcolor=\"white\">\r\n");
      out.write("       添加新物品\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <form name=\"form1\" action=\"AddServlet\" method=\"post\" onsubmit=\"return check3(this)\">\r\n");
      out.write("    <td align=\"center\">0");
      out.print(request.getAttribute("count"));
      out.write("</td>\r\n");
      out.write("    <td><input size=\"5\" type=\"text\" name=\"name\"></td>\r\n");
      out.write("    <td><input size=\"3\" type=\"text\" name=\"price\"></td>\r\n");
      out.write("    <td><input size=\"3\" type=\"text\" name=\"num\"></td>\r\n");
      out.write("    <td><input size=\"3\" type=\"text\" name=\"unit\"></td>\r\n");
      out.write("    <td align=\"center\"><input size=\"7\" type=\"submit\" name=\"submit\"  value=\"点击添加物品\"></td>\r\n");
      out.write("    </form>\r\n");
      out.write("    <td style=\"color:909090\">删除</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td colspan=\"5\" align=\"center\">所有产品一共￥:");
      out.print( request.getAttribute("sum").toString());
      out.write("</td>\r\n");
      out.write("    <td align=\"center\"><input type=\"submit\" value=\"点击提交表单\"></td>\r\n");
      out.write("    <td style=\"color:909090\">删除</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
